variables:
  UV_VERSION: 0.9
  PYTHON_VERSION: 3.14
  BASE_LAYER: bookworm
  UV_CACHE_DIR: .uv-cache
  UV_SYSTEM_PYTHON: 1

stages:
  - pre-commit
  - test

.default-uv-job:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  before_script:
    - apt-get update && apt-get install -y git
    - uv sync --all-extras --all-packages
  cache:
    key:
      files:
        - uv.lock
    paths:
      - $UV_CACHE_DIR
      - ~/.cache/pre-commit

pre-commit-check:
  stage: pre-commit
  extends: .default-uv-job
  script:
    - uv run pre-commit run --all-files

pytest:
  stage: test
  extends: .default-uv-job
  script:
    - uv run pytest
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      junit: reports/test.xml
      coverage_report:
        coverage_format: cobertura
        path: reports/coverage.xml
