[project]
name = "L3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "James Clause", email = "clause@udel.edu" }]
requires-python = ">=3.14"
dependencies = ["pydantic>=2.12.3", "util"]
